name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for collaborating with the project by giving us feedback!'
          pr-message: 'Thank you for collaborating with the project to help us improve! We hope this CLI is useful to you. Cheers!'
